### ISSUE TITLE
Slow upload speeds with DW1560

### ISSUE THREAD

**Issue by aptonline** [MSzturc/Lenovo-T460-OpenCore#17]
I seem to be experiencing very slow, and sometimes no upload, speeds using this repo with my new DW1560 card.  Initially I put it down to a site issue but after testing with Ethernet on my T460 I pinpointed it as being an issue with the wifi.  I also made some local wifi check using open speed test which confirmed the issues, download speeds fine, uploads speeds not.  I wasn't sure if the card cables were connected correctly so I changed them over (see photo) but this did not improve things.  I've checked the `AirportBrcmFixup.kext` and its the latest version so not sure what is causing the issue.

Any help grateful.

![IMG_4002](https://user-images.githubusercontent.com/190136/91555503-0977d280-e929-11ea-8e15-76b2fc0ceed0.jpg)

**Comment by aptonline** [comment]
After obtained the maintenance manual for the T460 it appears the grey wire should go to main (▲ or J1) but switching this does not improve things.  So its either a Wi-fi card issue or a config issue.

**Comment by aptonline** [comment]
Seems I had a faulty wi-fi card, seller replaced and tested to be working for both download and upload speeds.

**Comment by MarkMorrow** [comment]
@aptonline ,

I also have DW1560 installed. Mine is T460s, but should be close enough.  I'm curious what method you used to  determine download/uploads speeds and what is correct for this setup?  Also might you know if this card is capable of supporting Apple's unlock with watch feature?  [I used this guide to install Big Sur, ](https://github.com/simprecicchiani/ThinkPad-T460s-macOS-OpenCore) and posted that question in the discussion, but since the guide offers intel and other broadcom card support they may not know.  Hoping you have a watch and would know if the card is capable under either Big Sur or Catalina when using OpenCore, and could provide pointers.  Thanks in advance.
